#Deriving the latest base image
FROM python:latest


#Labels as key value pair
LABEL Maintainer="prajkta128@gmail.com"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /home/prajkta/python

#to COPY the remote file at working directory in container
COPY test.py ./
# Now the structure looks like this '/usr/app/src/test.py'


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./test.py"]

# creter docker file and html code in one folder.
# step0 :- docker image build -t  python:0.01 .
# step1 :- docker images
# step4 :- docker run python:0.0.1
# step9:- docker container rm -f container-id



# --------------------------------------
# go to docker hun and pull the image nginx
# docker run --name some-nginx -d -p 8080:80 some-content-nginx
# docker ps
# docker rm -f container